package com.trading.grpc;

import com.trading.entity.Order;
import com.trading.repository.OrderRepository;
import com.trading.service.RiskEngine;
import com.trading.service.RiskEngine.RiskResult;

import io.grpc.stub.StreamObserver;
import lombok.extern.slf4j.Slf4j;
import net.devh.boot.grpc.client.inject.GrpcClient;
import net.devh.boot.grpc.server.service.GrpcService;

// ── Generated by Gradle protobuf plugin from proto/*.proto ─────────────────
// These classes are created in build/generated/source/proto/main/ when you
// run: ./gradlew generateProto  (or just: ./gradlew build)
// The java_package option in the .proto files sets the package to com.trading.proto
import com.trading.proto.ExecutionServiceGrpc;
import com.trading.proto.OrchestratorServiceGrpc;
import com.trading.proto.PlaceOrderRequest;
import com.trading.proto.PlaceOrderResponse;
import com.trading.proto.GetPortfolioRequest;
import com.trading.proto.GetPortfolioResponse;
import com.trading.proto.StreamTradesRequest;
import com.trading.proto.SubmitOrderRequest;
import com.trading.proto.SubmitOrderResponse;
import com.trading.proto.Trade;
import com.trading.proto.OrderStatus;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * OrchestratorServiceImpl — the gRPC server implementation for Phase 3.
 *
 * This class implements the OrchestratorService defined in services.proto
 * and is the central hub of the entire platform.
 *
 * It receives requests from:
 *   - The Python Strategy engine (PlaceOrder with signals)
 *   - The REST API layer (PlaceOrder from user HTTP calls)
 *
 * It calls out to:
 *   - The C++ ExecutionService (SubmitOrder on port 50051)
 *   - PostgreSQL (via repositories injected through the service classes)
 *
 * ┌─────────────────────────────────────────────────────────────┐
 *  PlaceOrder flow:
 *   1. Validate input (non-null fields, valid symbol, etc.)
 *   2. Generate a UUID for the order
 *   3. Persist the order to DB with status=PENDING
 *   4. Run RiskEngine.validate() — reject if it fails
 *   5. Forward to C++ engine via engineStub.submitOrder()
 *   6. Update order status in DB based on engine response
 *   7. Return PlaceOrderResponse to caller
 * └─────────────────────────────────────────────────────────────┘
 */
@Slf4j
@GrpcService   // net.devh annotation — registers this as a gRPC service on port 50052
public class OrchestratorServiceImpl
        extends OrchestratorServiceGrpc.OrchestratorServiceImplBase {

    // ── Injected dependencies ──────────────────────────────────────────────

    private final RiskEngine      riskEngine;
    private final OrderRepository orderRepository;

    // Injects a managed gRPC channel to cpp-engine (configured in application.yml)
    @GrpcClient("cpp-engine")
    private ExecutionServiceGrpc.ExecutionServiceBlockingStub engineStub;

    public OrchestratorServiceImpl(RiskEngine riskEngine,
                                   OrderRepository orderRepository) {
        this.riskEngine      = riskEngine;
        this.orderRepository = orderRepository;
    }

    // ─────────────────────────────────────────────────────────────────────
    //  PlaceOrder RPC
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Receives an order from the Python strategy or REST client,
     * validates it, and forwards it to the C++ matching engine.
     *
     * @param request  contains a trading.Order proto message
     * @param responseObserver used to send back the PlaceOrderResponse
     */
    @Override
    public void placeOrder(PlaceOrderRequest request,
                           StreamObserver<PlaceOrderResponse> responseObserver) {

        // TODO: Step 1 — extract the order from request.getOrder()
        //       Validate required fields: order_id should be empty (we generate it),
        //       user_id, symbol, side, type, quantity must be present.
        //       If invalid → respond with REJECTED and return.

        // TODO: Step 2 — generate a UUID and create an Order entity
        //   UUID orderId = UUID.randomUUID();
        //   Order order = new Order();
        //   order.setId(orderId);
        //   order.setUserId(UUID.fromString(proto.getUserId()));
        //   order.setSymbol(proto.getSymbol());
        //   order.setSide(proto.getSide().name());   // "BUY" or "SELL"
        //   order.setType(proto.getType().name());   // "LIMIT" or "MARKET"
        //   order.setQuantity(BigDecimal.valueOf(proto.getQuantity()));
        //   order.setPrice(BigDecimal.valueOf(proto.getPrice()));
        //   order.setCreatedAt(OffsetDateTime.now());
        //   order.setUpdatedAt(OffsetDateTime.now());

        // TODO: Step 3 — persist the order with status=PENDING
        //   orderRepository.save(order);

        // TODO: Step 4 — run risk check
        //   RiskResult risk = riskEngine.validate(order);
        //   if (!risk.approved()) {
        //       order.setStatus("REJECTED");
        //       orderRepository.save(order);
        //       respond with OrderStatus.REJECTED + risk.reason()
        //       return;
        //   }

        // TODO: Step 5 — build the proto to send to the C++ engine
        //   The engine expects a trading.SubmitOrderRequest with a fully populated Order.
        //   Important: set order_id to orderId.toString() so the engine uses OUR uuid.
        //
        //   trading.Order engineOrder = trading.Order.newBuilder()
        //       .setOrderId(orderId.toString())
        //       .setUserId(order.getUserId().toString())
        //       .setSymbol(order.getSymbol())
        //       .setSide(proto.getSide())
        //       .setType(proto.getType())
        //       .setQuantity(proto.getQuantity())
        //       .setPrice(proto.getPrice())
        //       .setTimestampMs(System.currentTimeMillis())
        //       .build();
        //
        //   SubmitOrderRequest engineRequest = SubmitOrderRequest.newBuilder()
        //       .setOrder(engineOrder)
        //       .build();

        // TODO: Step 6 — call the C++ engine (blocking call)
        //   SubmitOrderResponse engineResponse = engineStub.submitOrder(engineRequest);
        //   Map engineResponse.getStatus() back to a DB status string and update DB.
        //   orderRepository.save(order);

        // TODO: Step 7 — build and send the response
        //   PlaceOrderResponse response = PlaceOrderResponse.newBuilder()
        //       .setOrderId(orderId.toString())
        //       .setStatus(engineResponse.getStatus())
        //       .setMessage(engineResponse.getMessage())
        //       .build();
        //   responseObserver.onNext(response);
        //   responseObserver.onCompleted();

        throw new UnsupportedOperationException("TODO: implement placeOrder");
    }

    // ─────────────────────────────────────────────────────────────────────
    //  GetPortfolio RPC
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Returns the current portfolio snapshot for a user.
     * Reads from PostgreSQL — does NOT call the C++ engine.
     *
     * @param request  contains user_id
     * @param responseObserver returns a GetPortfolioResponse containing a Portfolio proto
     */
    @Override
    public void getPortfolio(GetPortfolioRequest request,
                             StreamObserver<GetPortfolioResponse> responseObserver) {

        // TODO: Step 1 — parse user_id from request.getUserId()
        //   UUID userId = UUID.fromString(request.getUserId());

        // TODO: Step 2 — load Portfolio entity from DB
        //   portfolioRepository.findByUserId(userId) → if empty, respond with error

        // TODO: Step 3 — load Positions for this portfolio
        //   positionRepository.findByPortfolioId(portfolio.getId())

        // TODO: Step 4 — build the trading.Portfolio proto
        //   Build a list of trading.Position protos from the Position entities.
        //   trading.Portfolio protoPortfolio = trading.Portfolio.newBuilder()
        //       .setUserId(request.getUserId())
        //       .setCash(portfolio.getCash().doubleValue())
        //       .addAllPositions(positionProtos)
        //       .build();

        // TODO: Step 5 — send response
        //   responseObserver.onNext(GetPortfolioResponse.newBuilder()
        //       .setPortfolio(protoPortfolio).build());
        //   responseObserver.onCompleted();

        throw new UnsupportedOperationException("TODO: implement getPortfolio");
    }

    // ─────────────────────────────────────────────────────────────────────
    //  StreamTrades RPC
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Streams live trade confirmations to a client (e.g. a user's browser via WebSocket).
     *
     * This works by opening a StreamExecutions call TO the C++ engine,
     * then forwarding each Trade it receives TO the client connected here.
     *
     * It's essentially a proxy stream: C++ → Java → Python/REST client
     *
     * @param request  user_id and optional symbol filter
     * @param responseObserver the outbound stream to the calling client
     */
    @Override
    public void streamTrades(StreamTradesRequest request,
                             StreamObserver<Trade> responseObserver) {

        // TODO: Open a streaming call to the C++ engine.
        //       Use the ASYNC stub (not blocking) for streaming:
        //
        //   ExecutionServiceGrpc.ExecutionServiceStub asyncStub = ...;
        //   StreamExecutionsRequest engineRequest = StreamExecutionsRequest.newBuilder()
        //       .setSymbol(request.getSymbol())
        //       .build();
        //
        //   asyncStub.streamExecutions(engineRequest, new StreamObserver<Trade>() {
        //       @Override public void onNext(Trade trade) {
        //           // Optional: filter by request.getUserId() if trade involves this user
        //           responseObserver.onNext(trade);
        //       }
        //       @Override public void onError(Throwable t) {
        //           responseObserver.onError(t);
        //       }
        //       @Override public void onCompleted() {
        //           responseObserver.onCompleted();
        //       }
        //   });

        throw new UnsupportedOperationException("TODO: implement streamTrades");
    }
}
