package com.trading.grpc;

import com.trading.entity.Order;
import com.trading.entity.Portfolio;
import com.trading.entity.Position;
import com.trading.repository.OrderRepository;
import com.trading.repository.PortfolioRepository;
import com.trading.repository.PositionRepository;
import com.trading.service.RiskEngine;
import com.trading.service.RiskEngine.RiskResult;

import io.grpc.Status;
import io.grpc.stub.StreamObserver;
import lombok.extern.slf4j.Slf4j;
import net.devh.boot.grpc.client.inject.GrpcClient;
import net.devh.boot.grpc.server.service.GrpcService;

// ── Generated by Gradle protobuf plugin from proto/*.proto ─────────────────
import com.trading.proto.ExecutionServiceGrpc;
import com.trading.proto.OrchestratorServiceGrpc;
import com.trading.proto.PlaceOrderRequest;
import com.trading.proto.PlaceOrderResponse;
import com.trading.proto.GetPortfolioRequest;
import com.trading.proto.GetPortfolioResponse;
import com.trading.proto.StreamTradesRequest;
import com.trading.proto.StreamExecutionsRequest;
import com.trading.proto.SubmitOrderRequest;
import com.trading.proto.SubmitOrderResponse;
import com.trading.proto.Trade;
import com.trading.proto.OrderStatus;
import com.trading.proto.OrderSide;
import com.trading.proto.OrderType;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * OrchestratorServiceImpl — the gRPC server implementation for Phase 3.
 *
 * This class implements the OrchestratorService defined in services.proto
 * and is the central hub of the entire platform.
 */
@Slf4j
@GrpcService   // net.devh annotation — registers this as a gRPC service on port 50052
public class OrchestratorServiceImpl
        extends OrchestratorServiceGrpc.OrchestratorServiceImplBase {

    // ── Injected dependencies ──────────────────────────────────────────────

    private final RiskEngine          riskEngine;
    private final OrderRepository     orderRepository;
    private final PortfolioRepository portfolioRepository;
    private final PositionRepository  positionRepository;

    // Injects a managed gRPC channel to cpp-engine (configured in application.yml)
    @GrpcClient("cpp-engine")
    private ExecutionServiceGrpc.ExecutionServiceBlockingStub engineStub;

    @GrpcClient("cpp-engine")
    private ExecutionServiceGrpc.ExecutionServiceStub asyncEngineStub;

    public OrchestratorServiceImpl(RiskEngine riskEngine,
                                   OrderRepository orderRepository,
                                   PortfolioRepository portfolioRepository,
                                   PositionRepository positionRepository) {
        this.riskEngine          = riskEngine;
        this.orderRepository     = orderRepository;
        this.portfolioRepository = portfolioRepository;
        this.positionRepository  = positionRepository;
    }

    // ─────────────────────────────────────────────────────────────────────
    //  PlaceOrder RPC
    // ─────────────────────────────────────────────────────────────────────

    @Override
    public void placeOrder(PlaceOrderRequest request,
                           StreamObserver<PlaceOrderResponse> responseObserver) {

        com.trading.proto.Order proto = request.getOrder();

        // 1. Basic validation
        if (proto.getUserId().isBlank() || proto.getSymbol().isBlank() ||
            proto.getQuantity() <= 0 ||
            proto.getSide() == OrderSide.ORDER_SIDE_UNSPECIFIED ||
            proto.getType() == OrderType.ORDER_TYPE_UNSPECIFIED) {

            responseObserver.onNext(PlaceOrderResponse.newBuilder()
                .setStatus(OrderStatus.REJECTED)
                .setMessage("Invalid order parameters")
                .build());
            responseObserver.onCompleted();
            return;
        }

        UUID userId;
        try {
            userId = UUID.fromString(proto.getUserId());
        } catch (IllegalArgumentException e) {
            responseObserver.onNext(PlaceOrderResponse.newBuilder()
                .setStatus(OrderStatus.REJECTED)
                .setMessage("Invalid user_id format (must be UUID)")
                .build());
            responseObserver.onCompleted();
            return;
        }

        // 2. Generate UUID & create entity
        UUID orderId = UUID.randomUUID();
        Order order = new Order();
        order.setId(orderId);
        order.setUserId(userId);
        order.setSymbol(proto.getSymbol());
        order.setSide(proto.getSide().name());
        order.setType(proto.getType().name());
        order.setQuantity(BigDecimal.valueOf(proto.getQuantity()));
        order.setPrice(BigDecimal.valueOf(proto.getPrice()));
        order.setStatus("PENDING");
        order.setCreatedAt(OffsetDateTime.now());
        order.setUpdatedAt(OffsetDateTime.now());

        // 3. Persist with status=PENDING
        orderRepository.save(order);

        // 4. Run risk check
        RiskResult risk = riskEngine.validate(order);
        if (!risk.approved()) {
            order.setStatus("REJECTED");
            order.setUpdatedAt(OffsetDateTime.now());
            orderRepository.save(order);

            responseObserver.onNext(PlaceOrderResponse.newBuilder()
                .setOrderId(orderId.toString())
                .setStatus(OrderStatus.REJECTED)
                .setMessage("Risk check failed: " + risk.reason())
                .build());
            responseObserver.onCompleted();
            return;
        }

        // 5. Update order to VALIDATED
        order.setStatus("VALIDATED");
        order.setUpdatedAt(OffsetDateTime.now());
        orderRepository.save(order);

        // 6. Build proto for C++ engine
        com.trading.proto.Order engineOrder = com.trading.proto.Order.newBuilder()
            .setOrderId(orderId.toString())
            .setUserId(order.getUserId().toString())
            .setSymbol(order.getSymbol())
            .setSide(proto.getSide())
            .setType(proto.getType())
            .setQuantity(proto.getQuantity())
            .setPrice(proto.getPrice())
            .setTimestampMs(System.currentTimeMillis())
            .setStatus(OrderStatus.VALIDATED)
            .build();

        SubmitOrderRequest engineRequest = SubmitOrderRequest.newBuilder()
            .setOrder(engineOrder)
            .build();

        // 7. Forward to C++ engine
        try {
            SubmitOrderResponse engineResponse = engineStub.submitOrder(engineRequest);
            order.setStatus(engineResponse.getStatus().name());
            order.setUpdatedAt(OffsetDateTime.now());
            orderRepository.save(order);

            responseObserver.onNext(PlaceOrderResponse.newBuilder()
                .setOrderId(orderId.toString())
                .setStatus(engineResponse.getStatus())
                .setMessage(engineResponse.getMessage())
                .build());
            responseObserver.onCompleted();
        } catch (Exception e) {
            log.error("[ORCHESTRATOR] C++ Engine call failed for order {}: {}", orderId, e.getMessage());
            order.setStatus("REJECTED");
            order.setUpdatedAt(OffsetDateTime.now());
            orderRepository.save(order);

            responseObserver.onNext(PlaceOrderResponse.newBuilder()
                .setOrderId(orderId.toString())
                .setStatus(OrderStatus.REJECTED)
                .setMessage("Engine unavailable: " + e.getMessage())
                .build());
            responseObserver.onCompleted();
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    //  GetPortfolio RPC
    // ─────────────────────────────────────────────────────────────────────

    @Override
    public void getPortfolio(GetPortfolioRequest request,
                             StreamObserver<GetPortfolioResponse> responseObserver) {

        UUID userId;
        try {
            userId = UUID.fromString(request.getUserId());
        } catch (IllegalArgumentException e) {
            responseObserver.onError(Status.INVALID_ARGUMENT
                .withDescription("Invalid UUID format: " + request.getUserId())
                .asRuntimeException());
            return;
        }

        Optional<Portfolio> portfolioOpt = portfolioRepository.findByUserId(userId);
        if (portfolioOpt.isEmpty()) {
            responseObserver.onError(Status.NOT_FOUND
                .withDescription("Portfolio not found for user: " + userId)
                .asRuntimeException());
            return;
        }
        Portfolio portfolio = portfolioOpt.get();

        List<Position> positions = positionRepository.findByPortfolioId(portfolio.getId());
        List<com.trading.proto.Position> positionProtos = positions.stream()
            .map(pos -> com.trading.proto.Position.newBuilder()
                .setSymbol(pos.getSymbol())
                .setQuantity(pos.getQuantity().doubleValue())
                .setAverageCost(pos.getAverageCost().doubleValue())
                .setCurrentPnl(0.0)
                .build())
            .toList();

        com.trading.proto.Portfolio protoPortfolio = com.trading.proto.Portfolio.newBuilder()
            .setUserId(request.getUserId())
            .setCash(portfolio.getCash().doubleValue())
            .addAllPositions(positionProtos)
            .build();

        responseObserver.onNext(GetPortfolioResponse.newBuilder()
            .setPortfolio(protoPortfolio)
            .build());
        responseObserver.onCompleted();
    }

    // ─────────────────────────────────────────────────────────────────────
    //  StreamTrades RPC
    // ─────────────────────────────────────────────────────────────────────

    @Override
    public void streamTrades(StreamTradesRequest request,
                             StreamObserver<Trade> responseObserver) {

        StreamExecutionsRequest engineRequest = StreamExecutionsRequest.newBuilder()
            .setSymbol(request.getSymbol())
            .build();

        asyncEngineStub.streamExecutions(engineRequest, new StreamObserver<Trade>() {
            @Override
            public void onNext(Trade trade) {
                responseObserver.onNext(trade);
            }

            @Override
            public void onError(Throwable t) {
                log.error("[STREAM_TRADES] Error streaming from C++ engine: {}", t.getMessage());
                responseObserver.onError(t);
            }

            @Override
            public void onCompleted() {
                responseObserver.onCompleted();
            }
        });
    }
}
