package com.trading.grpc;

import com.trading.entity.Order;
import com.trading.entity.Trade;
import com.trading.repository.OrderRepository;
import com.trading.repository.TradeRepository;
import com.trading.service.PortfolioService;

import io.grpc.stub.StreamObserver;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.devh.boot.grpc.client.inject.GrpcClient;
import org.springframework.stereotype.Component;

// ── Generated by Gradle protobuf plugin from proto/*.proto ─────────────────
// Run: ./gradlew generateProto  to create these in build/generated/source/proto/main/
import com.trading.proto.ExecutionServiceGrpc;
import com.trading.proto.StreamExecutionsRequest;
// NOTE: com.trading.proto.Trade is used fully-qualified below to avoid collision
//       with com.trading.entity.Trade (both are named 'Trade')

import java.math.BigDecimal;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.UUID;

/**
 * TradeConsumer — connects to the C++ engine's StreamExecutions RPC on startup
 * and processes every trade the matching engine produces.
 *
 * Responsibilities for each incoming Trade:
 *   1. Persist the trade to the `trades` table
 *   2. Update the buyer's and seller's portfolios via PortfolioService
 *   3. Update both orders' statuses in the DB (PARTIALLY_FILLED or FILLED)
 *   4. Broadcast the trade over WebSocket so UIs update in real-time
 *
 * This runs on a background thread once the application starts (@PostConstruct).
 * If the C++ engine is not yet available, the gRPC call will block until it is
 * (with retry/backoff configured in application.yml).
 *
 * Connection diagram:
 *   C++ engine :50051
 *      └─ StreamExecutions (server-side stream)
 *            └─► TradeConsumer.onNext(Trade)
 *                    ├─► TradeRepository.save()
 *                    ├─► PortfolioService.applyTrade()
 *                    ├─► OrderRepository.save() (update status)
 *                    └─► WebSocket broadcast (optional Phase 3 feature)
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class TradeConsumer {

    private final TradeRepository   tradeRepository;
    private final OrderRepository   orderRepository;
    private final PortfolioService  portfolioService;

    // The async stub lets us open a server-streaming call without blocking the thread
    @GrpcClient("cpp-engine")
    private ExecutionServiceGrpc.ExecutionServiceStub asyncEngineStub;

    /**
     * Called once Spring finishes wiring all beans.
     * Opens a persistent streaming connection to the C++ engine.
     */
    @PostConstruct
    public void startListening() {
        // TODO: Build the StreamExecutions request.
        //       Leave symbol empty to receive ALL trades across all symbols.
        //
        //   StreamExecutionsRequest request = StreamExecutionsRequest.newBuilder()
        //       .setSymbol("")   // empty = subscribe to everything
        //       .build();

        // TODO: Open the stream using the async stub.
        //       The callbacks below (onNext, onError, onCompleted) fire on the gRPC thread.
        //
        //   asyncEngineStub.streamExecutions(request, new StreamObserver<com.trading.proto.Trade>() {
        //
        //       @Override
        //       public void onNext(com.trading.proto.Trade trade) {
        //           handleTrade(trade);
        //       }
        //
        //       @Override
        //       public void onError(Throwable t) {
        //           log.error("[TRADE CONSUMER] Stream error: {}", t.getMessage());
        //           // TODO (optional): implement reconnect with exponential backoff
        //       }
        //
        //       @Override
        //       public void onCompleted() {
        //           log.warn("[TRADE CONSUMER] Stream closed by engine");
        //       }
        //   });

        log.info("[TRADE CONSUMER] TODO: start listening to C++ engine stream");
    }

    // ─────────────────────────────────────────────────────────────────────
    //  Process a single matched trade
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Called for every trade the C++ engine produces.
     * This is the core of the post-execution lifecycle.
     *
     * @param proto the Trade proto message from the engine
     */
    private void handleTrade(com.trading.proto.Trade proto) {
        log.info("[TRADE] {} {} qty={} @ {}",
            proto.getSymbol(), proto.getTradeId(),
            proto.getQuantity(), proto.getPrice());

        // TODO: Step 1 — Convert proto to Trade entity and persist it.
        //   Trade trade = new Trade();
        //   trade.setId(UUID.fromString(proto.getTradeId()));
        //   trade.setBuyOrderId(UUID.fromString(proto.getBuyOrderId()));
        //   trade.setSellOrderId(UUID.fromString(proto.getSellOrderId()));
        //   trade.setSymbol(proto.getSymbol());
        //   trade.setQuantity(BigDecimal.valueOf(proto.getQuantity()));
        //   trade.setPrice(BigDecimal.valueOf(proto.getPrice()));
        //   trade.setExecutedAt(OffsetDateTime.ofInstant(
        //       Instant.ofEpochMilli(proto.getTimestampMs()), ZoneOffset.UTC));
        //   tradeRepository.save(trade);

        // TODO: Step 2 — Load the buyer and seller orders from DB.
        //   Optional<Order> buyOrder  = orderRepository.findById(trade.getBuyOrderId());
        //   Optional<Order> sellOrder = orderRepository.findById(trade.getSellOrderId());
        //   Handle the case where orders are not found (log + skip portfolio update).

        // TODO: Step 3 — Apply trade effects to portfolios.
        //   portfolioService.applyTrade(trade, buyOrder.get(), sellOrder.get());

        // TODO: Step 4 — Update order statuses.
        //   The engine doesn't push status updates — you need to check fill progress.
        //   Simple approach: mark both orders as FILLED.
        //   Advanced approach: track filled_qty and set PARTIALLY_FILLED vs FILLED.

        // TODO (optional): Step 5 — Broadcast over WebSocket.
        //   Inject a SimpMessagingTemplate and send to "/topic/trades"
        //   so any connected browser dashboard updates in real-time.
    }
}
