package com.trading.grpc;

import com.trading.entity.Order;
import com.trading.entity.Trade;
import com.trading.repository.OrderRepository;
import com.trading.repository.TradeRepository;
import com.trading.service.PortfolioService;

import io.grpc.stub.StreamObserver;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.devh.boot.grpc.client.inject.GrpcClient;
import org.springframework.stereotype.Component;

// ── Generated by Gradle protobuf plugin from proto/*.proto ─────────────────
// Run: ./gradlew generateProto  to create these in build/generated/source/proto/main/
import com.trading.proto.ExecutionServiceGrpc;
import com.trading.proto.StreamExecutionsRequest;
// NOTE: com.trading.proto.Trade is used fully-qualified below to avoid collision
//       with com.trading.entity.Trade (both are named 'Trade')

import java.math.BigDecimal;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * TradeConsumer — connects to the C++ engine's StreamExecutions RPC on startup
 * and processes every trade the matching engine produces.
 *
 * Responsibilities for each incoming Trade:
 *   1. Persist the trade to the `trades` table
 *   2. Update the buyer's and seller's portfolios via PortfolioService
 *   3. Update both orders' statuses in the DB (PARTIALLY_FILLED or FILLED)
 *   4. Broadcast the trade over WebSocket so UIs update in real-time
 *
 * This runs on a background thread once the application starts (@PostConstruct).
 * If the C++ engine is not yet available, the gRPC call will block until it is
 * (with retry/backoff configured in application.yml).
 *
 * Connection diagram:
 *   C++ engine :50051
 *      └─ StreamExecutions (server-side stream)
 *            └─► TradeConsumer.onNext(Trade)
 *                    ├─► TradeRepository.save()
 *                    ├─► PortfolioService.applyTrade()
 *                    ├─► OrderRepository.save() (update status)
 *                    └─► WebSocket broadcast (optional Phase 3 feature)
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class TradeConsumer {

    private final TradeRepository   tradeRepository;
    private final OrderRepository   orderRepository;
    private final PortfolioService  portfolioService;

    // The async stub lets us open a server-streaming call without blocking the thread
    @GrpcClient("cpp-engine")
    private ExecutionServiceGrpc.ExecutionServiceStub asyncEngineStub;

    /**
     * Called once Spring finishes wiring all beans.
     * Opens a persistent streaming connection to the C++ engine.
     */
    @PostConstruct
    public void startListening() {
        StreamExecutionsRequest request = StreamExecutionsRequest.newBuilder()
            .setSymbol("")   // empty = subscribe to all symbols
            .build();

        asyncEngineStub.streamExecutions(request, new StreamObserver<com.trading.proto.Trade>() {
            @Override
            public void onNext(com.trading.proto.Trade trade) {
                try {
                    handleTrade(trade);
                } catch (Exception e) {
                    log.error("[TRADE CONSUMER] Error processing trade {}: {}", trade.getTradeId(), e.getMessage(), e);
                }
            }

            @Override
            public void onError(Throwable t) {
                log.error("[TRADE CONSUMER] Stream error from C++ engine: {}", t.getMessage());
            }

            @Override
            public void onCompleted() {
                log.warn("[TRADE CONSUMER] Stream closed by C++ engine");
            }
        });

        log.info("[TRADE CONSUMER] Subscribed to C++ engine executions stream");
    }

    // ─────────────────────────────────────────────────────────────────────
    //  Process a single matched trade
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Called for every trade the C++ engine produces.
     * This is the core of the post-execution lifecycle.
     *
     * @param proto the Trade proto message from the engine
     */
    private void handleTrade(com.trading.proto.Trade proto) {
        log.info("[TRADE] Executed {} {} qty={} @ {}",
            proto.getSymbol(), proto.getTradeId(),
            proto.getQuantity(), proto.getPrice());

        // 1. Convert proto to entity and persist
        Trade trade = new Trade();
        UUID tradeId;
        try {
            tradeId = (proto.getTradeId() == null || proto.getTradeId().isBlank())
                ? UUID.randomUUID()
                : UUID.fromString(proto.getTradeId());
        } catch (IllegalArgumentException e) {
            tradeId = UUID.randomUUID();
        }
        trade.setId(tradeId);

        trade.setBuyOrderId(UUID.fromString(proto.getBuyOrderId()));
        trade.setSellOrderId(UUID.fromString(proto.getSellOrderId()));
        trade.setSymbol(proto.getSymbol());
        trade.setQuantity(BigDecimal.valueOf(proto.getQuantity()));
        trade.setPrice(BigDecimal.valueOf(proto.getPrice()));

        long ts = proto.getTimestampMs() > 0 ? proto.getTimestampMs() : System.currentTimeMillis();
        trade.setExecutedAt(OffsetDateTime.ofInstant(Instant.ofEpochMilli(ts), ZoneOffset.UTC));
        tradeRepository.save(trade);

        // 2. Load orders
        Optional<Order> buyOrderOpt  = orderRepository.findById(trade.getBuyOrderId());
        Optional<Order> sellOrderOpt = orderRepository.findById(trade.getSellOrderId());

        if (buyOrderOpt.isEmpty() || sellOrderOpt.isEmpty()) {
            log.warn("[TRADE CONSUMER] Missing order(s) for trade {}: buyOrder present={}, sellOrder present={}",
                trade.getId(), buyOrderOpt.isPresent(), sellOrderOpt.isPresent());
            return;
        }

        Order buyOrder = buyOrderOpt.get();
        Order sellOrder = sellOrderOpt.get();

        // 3. Apply trade effects to portfolios
        portfolioService.applyTrade(trade, buyOrder, sellOrder);

        // 4. Update order statuses
        updateOrderStatus(buyOrder, true);
        updateOrderStatus(sellOrder, false);
    }

    private void updateOrderStatus(Order order, boolean isBuy) {
        List<Trade> trades = isBuy
            ? tradeRepository.findByBuyOrderId(order.getId())
            : tradeRepository.findBySellOrderId(order.getId());

        BigDecimal filledQty = trades.stream()
            .map(Trade::getQuantity)
            .reduce(BigDecimal.ZERO, BigDecimal::add);

        if (filledQty.compareTo(order.getQuantity()) >= 0) {
            order.setStatus("FILLED");
        } else {
            order.setStatus("PARTIALLY_FILLED");
        }
        order.setUpdatedAt(OffsetDateTime.now());
        orderRepository.save(order);
    }
}
