package com.trading.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity mapped to the `orders` table (infra/db/init.sql).
 *
 * The orchestrator writes an Order record the moment an order arrives
 * (status = PENDING), then updates its status as the C++ engine responds.
 *
 * Lifecycle:
 *   PENDING → VALIDATED → PARTIALLY_FILLED / FILLED / CANCELLED / REJECTED
 *
 * The order_id (UUID) is generated HERE in Java and passed to the C++ engine.
 * The engine uses this same ID, so we can correlate engine responses back to
 * the DB row without a second round-trip.
 */
@Entity
@Table(name = "orders")
@Getter @Setter @NoArgsConstructor
public class Order {

    /** UUID generated by the orchestrator before forwarding to the C++ engine. */
    @Id
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(nullable = false, length = 20)
    private String symbol;

    /**
     * "BUY" or "SELL" — stored as VARCHAR, constrained by the DB CHECK.
     * Maps to trading.OrderSide in the proto.
     */
    @Column(nullable = false, length = 4)
    private String side;

    /**
     * "LIMIT" or "MARKET" — stored as VARCHAR, constrained by the DB CHECK.
     * Maps to trading.OrderType in the proto.
     */
    @Column(nullable = false, length = 6)
    private String type;

    @Column(nullable = false, precision = 18, scale = 8)
    private BigDecimal quantity;

    /**
     * Limit price. NULL for MARKET orders (engine ignores it anyway).
     */
    @Column(precision = 18, scale = 8)
    private BigDecimal price;

    /**
     * Current lifecycle status.
     * Updated after the C++ engine responds (SubmitOrder → OrderStatus).
     */
    @Column(nullable = false, length = 20)
    private String status = "PENDING";

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
