package com.trading.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA entity mapped to the `trades` table (infra/db/init.sql).
 *
 * A Trade is created by the C++ engine whenever two orders match.
 * The orchestrator receives the trade (via StreamExecutions gRPC stream)
 * and persists it here, then updates the relevant portfolios.
 *
 * Key insight: one Order can generate MULTIPLE trades (partial fills).
 * Example: a BUY 100 AAPL may match against several SELL orders at
 * different price levels, producing one Trade record per match.
 */
@Entity
@Table(name = "trades")
@Getter @Setter @NoArgsConstructor
public class Trade {

    /** UUID generated by the C++ engine and forwarded via gRPC. */
    @Id
    private UUID id;

    /**
     * FK to orders.id — the buy side of the match.
     * The orchestrator can look this up to find the buyer's user_id
     * and update their portfolio.
     */
    @Column(name = "buy_order_id", nullable = false)
    private UUID buyOrderId;

    /**
     * FK to orders.id — the sell side of the match.
     * Used to find the seller's user_id and update their portfolio.
     */
    @Column(name = "sell_order_id", nullable = false)
    private UUID sellOrderId;

    @Column(nullable = false, length = 20)
    private String symbol;

    /** How many units were exchanged in this specific match. */
    @Column(nullable = false, precision = 18, scale = 8)
    private BigDecimal quantity;

    /** The price at which the match occurred (resting order's limit price). */
    @Column(nullable = false, precision = 18, scale = 8)
    private BigDecimal price;

    @Column(name = "executed_at", nullable = false)
    private OffsetDateTime executedAt;
}
